-- Adminer 4.7.1 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `items_id` int NOT NULL,
  `text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `rating` int DEFAULT NULL,
  `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `artists_id` (`items_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `comments` (`id`, `items_id`, `text`, `rating`, `date`) VALUES
(1,	1,	'Comments: <span>Edmodo completely changes the flow of the classroom from when I was a student. Before you lecture as students take notes, then hand out homework. There may be notes home for parents that you then have to keep track of. NO MORE! The LMS allows to you upload all of the notes ahead of time, keeping students engaged, paying attention and participating. The homework can be uploaded, reducing the environmental impact of education in our one-to-one iPad environment, reducing the &quot;I lost my homework/ You lost my homework&quot; issues (the internet could eat it, but haven&#39;t had that yet!), test functions reduce the amount of paper tests to complete. Finally, parent communication can largely occur through the application as well. It creates a &quot;one-stop-shop&quot; environment for the classroom and streamlines the classroom process for easy teaching, and easy learning.</span><br><br>\n\nPros: <span>I like the user-friendly interface of Edmodo. It seems similar to some social media platforms, making it easy for students to interact in a familiar way. There are good controls, such as restriction of student access, and read-only abilities. It is a great way for teachers to share work, notes, homework, etc with their classes, and interact with their students. Tests can also be handled through this platform. Students can also edit their work on the platform and receive feedback. Parent communication can also be handled through the application, which keeps them in the loop and helps students communicate at home with their parents regarding their work. Badges are a great motivator, especially in the gamified classroom. Students can also use the planner feature to keep track of and prioritize their work. It is also a way that teachers can interact with each other. Finally, the integration with other software, like Google, is pretty well handled.</span><br><br>\n\nCons: <span>The features of Edmodo can be a bit limited compared to some other LMSs, but it is also what makes it a simple enough tool to be easy to learn. The grading is simplistic and makes it harder to use in upper-level education. There has also been some interruption from ads, that while always school appropriate, are not always age appropriate, so it has created some questions in the classroom. I have had some problems with notifications, which support suggests is working as designed, but I would like to receive a bit more notification other than direct student messages. Parents would also like to have communications with them and their student come from one source for two-way communication, to one area, rather than what it is now, which is a bit wider spread across platforms. I have also had some issues with the display of my Chinese characters. Additionally, weighted grades, or varying the assignments by students would be helpful.</span><br><br>\n\n',	5,	'2020-05-22 15:44:35'),
(2,	1,	'Comments: <span>It&#39;s better to use a more commonly used UI for my LMS and as social media is just what I need Edmodo is just the right choice for me.<br>\nI am using the free plans and this is just fun. No dull UI to deal with and more enjoyable experience for my students.</span><br><br>\n\nPros: <span>I need to make a small tutorial on using photoshop and another image editing tool and found Edmodo has a lot of good reviews and feature that I need. It&#39;s free and does a very good job. Everything is cloud and does not need any effort once setup is just what I need. Sometimes training a new member is so time-consuming that I have made some basic video so I don&#39;t have to tell every, new team member, what to do.<br>\nCreating is fun and simple, even for me. I just uploaded ad that it, I found its better not to use YT. YT just have the video but I need a quiz to add so I can see they saw all the video and does not skip them.<br>\nI have also added some PSD for each class so all my member can send their own version of the edited photo and I can evaluate better.<br>\nEdmodo does not feel like LMS, it looks like more of a social media.</span><br><br>\n\nCons: <span>Well, social media is a two-way sword and sometimes I get complaints about its too easy and distractive.</span><br><br>\n\n',	5,	'2020-03-24 16:44:36'),
(3,	1,	'Comments: <span>We are not an educational institution like a School, College or University, but we at the hospital we offer Continuing Medical Education and Educational Training to the nurse staff and Doctors. Thats how we applied for this amazing platform without being an educational institution per-sé.<br>\nIt has worked for us very nice, until now, it has been well accepted among the users.</span><br><br>\n\nPros: <span>The user interface is very friendly (because its based in the UI of Facebook), so people get used to it very easily. I also like all the features that this platform offers.</span><br><br>\n\nCons: <span>Its a little bit tricky to use at the beginning even for the administrator if you don&#39;t have to much knowledge about it.</span><br><br>\n\n',	5,	'2020-03-24 16:44:36'),
(4,	1,	'Comments: <span>Overall, this is a good product for basic LMS needs, and worked for me in the beginning. After playing with a number of LMS apps and continuing to revamp my needs and redesign what online learning should look like, other LMS might just offer more in flexibility/features.</span><br><br>\n\nPros: <span>As is the case with most LMS apps out there, Edmodo does a nice job shifting from paper-digital, and giving students and teachers a platform to help manage and stay organized in the digital space. The fact that you can do a lot with the free platform is a big plus and educators Everything updates in real time, and is simple enough to put together your digital needs in one space.</span><br><br>\n\nCons: <span>To me, unlike some other LMS apps out there, Edmodo is limited. It doesn&#39;t have the modern or sleek look and design as others. It also doesn&#39;t have as interactive capability to embed a number of other apps/tools that teachers use daily into it. This is a must have when it comes to the digital classroom space. The more we can limit sending links and have one program integrate everything else into it, the better classroom management will be. I would also like to see some integrated features like virtual chats/video conferencing, and more enhanced lesson design features.</span><br><br>\n\n',	3,	'2020-05-24 15:44:36'),
(5,	1,	'Comments: <span>Edmodo was incredibly helpful for being able to post assignments, give students instant access to resources, and easy grading. I really enjoyed using it, even if it did have a few issues.</span><br><br>\n\nPros: <span>I was able to use Edmodo when my school district had a 1:1 iPad initiative. Students loved being able to come into the classroom and having one set place to be able to login and find what they needed for the day.</span><br><br>\n\nCons: <span>When I used it (2016-2018), the website felt a little clunky. The students liked using it, but it never seemed like it ran as smoothly as it could have, considering how long it had been around.</span><br><br>\n\n',	4,	'2020-05-10 15:44:36'),
(6,	1,	'Comments: <span>Edmodo completely changes the flow of the classroom from when I was a student. Before you lecture as students take notes, then hand out homework. There may be notes home for parents that you then have to keep track of. NO MORE! The LMS allows to you upload all of the notes ahead of time, keeping students engaged, paying attention and participating. The homework can be uploaded, reducing the environmental impact of education in our one-to-one iPad environment, reducing the &quot;I lost my homework/ You lost my homework&quot; issues (the internet could eat it, but haven&#39;t had that yet!), test functions reduce the amount of paper tests to complete. Finally, parent communication can largely occur through the application as well. It creates a &quot;one-stop-shop&quot; environment for the classroom and streamlines the classroom process for easy teaching, and easy learning.</span><br><br>\n\nPros: <span>I like the user-friendly interface of Edmodo. It seems similar to some social media platforms, making it easy for students to interact in a familiar way. There are good controls, such as restriction of student access, and read-only abilities. It is a great way for teachers to share work, notes, homework, etc with their classes, and interact with their students. Tests can also be handled through this platform. Students can also edit their work on the platform and receive feedback. Parent communication can also be handled through the application, which keeps them in the loop and helps students communicate at home with their parents regarding their work. Badges are a great motivator, especially in the gamified classroom. Students can also use the planner feature to keep track of and prioritize their work. It is also a way that teachers can interact with each other. Finally, the integration with other software, like Google, is pretty well handled.</span><br><br>\n\nCons: <span>The features of Edmodo can be a bit limited compared to some other LMSs, but it is also what makes it a simple enough tool to be easy to learn. The grading is simplistic and makes it harder to use in upper-level education. There has also been some interruption from ads, that while always school appropriate, are not always age appropriate, so it has created some questions in the classroom. I have had some problems with notifications, which support suggests is working as designed, but I would like to receive a bit more notification other than direct student messages. Parents would also like to have communications with them and their student come from one source for two-way communication, to one area, rather than what it is now, which is a bit wider spread across platforms. I have also had some issues with the display of my Chinese characters. Additionally, weighted grades, or varying the assignments by students would be helpful.</span><br><br>\n\n',	5,	'2020-03-26 16:49:02'),
(7,	1,	'Comments: <span>It&#39;s better to use a more commonly used UI for my LMS and as social media is just what I need Edmodo is just the right choice for me.<br>\nI am using the free plans and this is just fun. No dull UI to deal with and more enjoyable experience for my students.</span><br><br>\n\nPros: <span>I need to make a small tutorial on using photoshop and another image editing tool and found Edmodo has a lot of good reviews and feature that I need. It&#39;s free and does a very good job. Everything is cloud and does not need any effort once setup is just what I need. Sometimes training a new member is so time-consuming that I have made some basic video so I don&#39;t have to tell every, new team member, what to do.<br>\nCreating is fun and simple, even for me. I just uploaded ad that it, I found its better not to use YT. YT just have the video but I need a quiz to add so I can see they saw all the video and does not skip them.<br>\nI have also added some PSD for each class so all my member can send their own version of the edited photo and I can evaluate better.<br>\nEdmodo does not feel like LMS, it looks like more of a social media.</span><br><br>\n\nCons: <span>Well, social media is a two-way sword and sometimes I get complaints about its too easy and distractive.</span><br><br>\n\n',	5,	'2020-04-16 15:49:02'),
(8,	1,	'Comments: <span>We are not an educational institution like a School, College or University, but we at the hospital we offer Continuing Medical Education and Educational Training to the nurse staff and Doctors. Thats how we applied for this amazing platform without being an educational institution per-sé.<br>\nIt has worked for us very nice, until now, it has been well accepted among the users.</span><br><br>\n\nPros: <span>The user interface is very friendly (because its based in the UI of Facebook), so people get used to it very easily. I also like all the features that this platform offers.</span><br><br>\n\nCons: <span>Its a little bit tricky to use at the beginning even for the administrator if you don&#39;t have to much knowledge about it.</span><br><br>\n\n',	5,	'2020-04-03 15:49:02'),
(9,	1,	'Comments: <span>Overall, this is a good product for basic LMS needs, and worked for me in the beginning. After playing with a number of LMS apps and continuing to revamp my needs and redesign what online learning should look like, other LMS might just offer more in flexibility/features.</span><br><br>\n\nPros: <span>As is the case with most LMS apps out there, Edmodo does a nice job shifting from paper-digital, and giving students and teachers a platform to help manage and stay organized in the digital space. The fact that you can do a lot with the free platform is a big plus and educators Everything updates in real time, and is simple enough to put together your digital needs in one space.</span><br><br>\n\nCons: <span>To me, unlike some other LMS apps out there, Edmodo is limited. It doesn&#39;t have the modern or sleek look and design as others. It also doesn&#39;t have as interactive capability to embed a number of other apps/tools that teachers use daily into it. This is a must have when it comes to the digital classroom space. The more we can limit sending links and have one program integrate everything else into it, the better classroom management will be. I would also like to see some integrated features like virtual chats/video conferencing, and more enhanced lesson design features.</span><br><br>\n\n',	3,	'2020-03-28 16:49:02'),
(10,	1,	'Comments: <span>Edmodo was incredibly helpful for being able to post assignments, give students instant access to resources, and easy grading. I really enjoyed using it, even if it did have a few issues.</span><br><br>\n\nPros: <span>I was able to use Edmodo when my school district had a 1:1 iPad initiative. Students loved being able to come into the classroom and having one set place to be able to login and find what they needed for the day.</span><br><br>\n\nCons: <span>When I used it (2016-2018), the website felt a little clunky. The students liked using it, but it never seemed like it ran as smoothly as it could have, considering how long it had been around.</span><br><br>\n\n',	4,	'2020-05-09 15:49:02'),
(11,	1,	'Comments: <span>Edmodo completely changes the flow of the classroom from when I was a student. Before you lecture as students take notes, then hand out homework. There may be notes home for parents that you then have to keep track of. NO MORE! The LMS allows to you upload all of the notes ahead of time, keeping students engaged, paying attention and participating. The homework can be uploaded, reducing the environmental impact of education in our one-to-one iPad environment, reducing the &quot;I lost my homework/ You lost my homework&quot; issues (the internet could eat it, but haven&#39;t had that yet!), test functions reduce the amount of paper tests to complete. Finally, parent communication can largely occur through the application as well. It creates a &quot;one-stop-shop&quot; environment for the classroom and streamlines the classroom process for easy teaching, and easy learning.</span><br><br>\n\nPros: <span>I like the user-friendly interface of Edmodo. It seems similar to some social media platforms, making it easy for students to interact in a familiar way. There are good controls, such as restriction of student access, and read-only abilities. It is a great way for teachers to share work, notes, homework, etc with their classes, and interact with their students. Tests can also be handled through this platform. Students can also edit their work on the platform and receive feedback. Parent communication can also be handled through the application, which keeps them in the loop and helps students communicate at home with their parents regarding their work. Badges are a great motivator, especially in the gamified classroom. Students can also use the planner feature to keep track of and prioritize their work. It is also a way that teachers can interact with each other. Finally, the integration with other software, like Google, is pretty well handled.</span><br><br>\n\nCons: <span>The features of Edmodo can be a bit limited compared to some other LMSs, but it is also what makes it a simple enough tool to be easy to learn. The grading is simplistic and makes it harder to use in upper-level education. There has also been some interruption from ads, that while always school appropriate, are not always age appropriate, so it has created some questions in the classroom. I have had some problems with notifications, which support suggests is working as designed, but I would like to receive a bit more notification other than direct student messages. Parents would also like to have communications with them and their student come from one source for two-way communication, to one area, rather than what it is now, which is a bit wider spread across platforms. I have also had some issues with the display of my Chinese characters. Additionally, weighted grades, or varying the assignments by students would be helpful.</span><br><br>\n\n',	5,	'2020-05-20 15:51:27'),
(12,	1,	'Comments: <span>It&#39;s better to use a more commonly used UI for my LMS and as social media is just what I need Edmodo is just the right choice for me.<br>\nI am using the free plans and this is just fun. No dull UI to deal with and more enjoyable experience for my students.</span><br><br>\n\nPros: <span>I need to make a small tutorial on using photoshop and another image editing tool and found Edmodo has a lot of good reviews and feature that I need. It&#39;s free and does a very good job. Everything is cloud and does not need any effort once setup is just what I need. Sometimes training a new member is so time-consuming that I have made some basic video so I don&#39;t have to tell every, new team member, what to do.<br>\nCreating is fun and simple, even for me. I just uploaded ad that it, I found its better not to use YT. YT just have the video but I need a quiz to add so I can see they saw all the video and does not skip them.<br>\nI have also added some PSD for each class so all my member can send their own version of the edited photo and I can evaluate better.<br>\nEdmodo does not feel like LMS, it looks like more of a social media.</span><br><br>\n\nCons: <span>Well, social media is a two-way sword and sometimes I get complaints about its too easy and distractive.</span><br><br>\n\n',	5,	'2020-05-15 15:51:27'),
(13,	1,	'Comments: <span>We are not an educational institution like a School, College or University, but we at the hospital we offer Continuing Medical Education and Educational Training to the nurse staff and Doctors. Thats how we applied for this amazing platform without being an educational institution per-sé.<br>\nIt has worked for us very nice, until now, it has been well accepted among the users.</span><br><br>\n\nPros: <span>The user interface is very friendly (because its based in the UI of Facebook), so people get used to it very easily. I also like all the features that this platform offers.</span><br><br>\n\nCons: <span>Its a little bit tricky to use at the beginning even for the administrator if you don&#39;t have to much knowledge about it.</span><br><br>\n\n',	5,	'2020-04-18 15:51:27'),
(14,	1,	'Comments: <span>Overall, this is a good product for basic LMS needs, and worked for me in the beginning. After playing with a number of LMS apps and continuing to revamp my needs and redesign what online learning should look like, other LMS might just offer more in flexibility/features.</span><br><br>\n\nPros: <span>As is the case with most LMS apps out there, Edmodo does a nice job shifting from paper-digital, and giving students and teachers a platform to help manage and stay organized in the digital space. The fact that you can do a lot with the free platform is a big plus and educators Everything updates in real time, and is simple enough to put together your digital needs in one space.</span><br><br>\n\nCons: <span>To me, unlike some other LMS apps out there, Edmodo is limited. It doesn&#39;t have the modern or sleek look and design as others. It also doesn&#39;t have as interactive capability to embed a number of other apps/tools that teachers use daily into it. This is a must have when it comes to the digital classroom space. The more we can limit sending links and have one program integrate everything else into it, the better classroom management will be. I would also like to see some integrated features like virtual chats/video conferencing, and more enhanced lesson design features.</span><br><br>\n\n',	3,	'2020-05-20 15:51:28'),
(15,	1,	'Comments: <span>Edmodo was incredibly helpful for being able to post assignments, give students instant access to resources, and easy grading. I really enjoyed using it, even if it did have a few issues.</span><br><br>\n\nPros: <span>I was able to use Edmodo when my school district had a 1:1 iPad initiative. Students loved being able to come into the classroom and having one set place to be able to login and find what they needed for the day.</span><br><br>\n\nCons: <span>When I used it (2016-2018), the website felt a little clunky. The students liked using it, but it never seemed like it ran as smoothly as it could have, considering how long it had been around.</span><br><br>\n\n',	4,	'2020-05-02 15:51:29');

DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `capterra_id` int DEFAULT NULL,
  `image` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `items` (`id`, `name`, `description`, `capterra_id`, `image`, `website`, `date_created`) VALUES
(1,	'Edmodo',	'',	0,	'https://cdn0.capterra-static.com/logos/150/2091177.png',	'http://www.edmodo.com',	'2020-02-20 17:44:36');

-- 2020-02-26 15:51:24
